name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Secrets KEY
      env: |
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        touch devops/.env
        echo "SECRET_KEY='$DJANGO_SECRET_KEY'" > devops/.env
    - name: Setup Secrets DB USER
      env: |
        DATABASE_USER: ${{ secrets.DJANGO_DATABASE_USER }}
      run: |
        touch devops/.env
        echo "DATABASE_USER='$DATABASE_USER'" >> devops/.env
    - name: Setup Secrets DB PASSWORD
      env: |
        DATABASE_PASSWORD: ${{ secrets.DJANGO_DATABASE_PASSWORD }}
      run: |
        touch devops/.env
        echo "DATABASE_PASSWORD='$DATABASE_PASSWORD'" >> devops/.env
    - name: Setup Secrets DATABASE_HOST
      env: |
        DATABASE_HOST: ${{ secrets.DJANGO_DATABASE_HOST }}
      run: |
        touch devops/.env
        echo "DATABASE_HOST='$DATABASE_HOST'" >> devops/.env
    - name: Setup Secrets DATABASE_PORT
      env: |
        DATABASE_PORT: ${{ secrets.DJANGO_DATABASE_PORT }}
      run: |
        touch devops/.env
        echo "DATABASE_PORT='$DATABASE_PORT'" >> devops/.env
    - name: Run Tests
      run: |
        python manage.py test
